package com.music.dao;

import com.music.domain.Singer;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface SingerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table singer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    int insert(Singer singer);

    int insertSelective(Singer singer);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table singer
     *
     * @mbggenerated
     */
    List<Singer> selectByPrimaryKey(Integer sex);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table singer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Singer singer);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table singer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Singer record);

    List<Singer> allSinger();

}